apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: app-demo
  labels:
    app: nginx
data:
  index.html: |
    <html>
    <head><title>Pagina Servita da ConfigMap</title></head>
    <body>
      <h1>Benvenuto su Nginx in Kubernetes!</h1>
      <p>Questa pagina è stata caricata da una ConfigMap.</p>
    </body>
    </html>
