apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: app-demo
  labels:
    app: nginx
data:
  index.html: |
    <html>
    <head><title>Secret Management PoC</title></head>
    <body>
      <h1>Hello there!</h1>
      <p>This page is coming from a ConfigMap <path:argocd/data/app-demo#password></p>
    </body>
    </html>
