apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: app-demo
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
